76 integrate   add doctor on profile page
Group-2-Capstone-Alterra/FrontEnd pull request #86
Opened 2024-06-06 15:46 UTC by gilangr1440

2024-06-06 19:09 UTC, Kopalmuhamad reviewed
ada conflict mas

2024-06-07 07:19 UTC, gilangr1440 commented
> ada conflict mas

udah solved

2024-06-07 09:39 UTC, devanada requested changes

2024-06-07 09:39 UTC, devanada commented on src/pages/admin/module/add-doctor.tsx
>      console.log(values);
console.log tolong di hapusin ya @gilangr1440

2024-06-07 09:39 UTC, devanada commented on src/pages/admin/module/add-doctor.tsx
> +      console.log(error);
minta tolong error handling nya jangan pakai console.log, better pakai toast @gilangr1440

2024-06-07 09:49 UTC, gilangr1440 commented on src/pages/admin/module/add-doctor.tsx
> +      console.log(error);
untuk error yang ditampilkan ke user udah di handle di bagian try nya mas. kalo yang bawahnya itu error nya bukan untuk user

2024-06-07 09:51 UTC, gilangr1440 commented on src/pages/admin/module/add-doctor.tsx
>      console.log(values);
ok mas

2024-06-07 09:57 UTC, gilangr1440 commented on src/pages/admin/module/add-doctor.tsx
> +      console.log(error);
oh siap mas

2024-06-07 14:41 UTC, merged